package com.ticket.transport.common;

public enum NotificationType {
    NORMAL_NOTIFICATION,
    OPEN_BOOKING_NOTIFICATION,
    UPDATE_BOOKING_1ST_NOTIFICATION,
    UPDATE_BOOKING_2RD_NOTIFICATION,
    CONFIRM_BOOKING_SUCCESS,
    CONFIRM_BOOKING_FAIL,
    REJECT_BOOKING,
    CREATE_BOOKING_SUCCESS,
    CREATE_BOOKING_FAIL,
}
